### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by JohnLucaJF** [seanap/auto-m4b#3]
"The chapters are based on the mp3 tracks. A single mp3 file will become a single m4b with 1 chapter, also if the mp3 filenames are garbarge then your m4b chapternames will be terrible as well. See section on Chapters below for how to manually adjust."

Any plans to enable it to merge multiple mp3 files into a single m4b  ?

Thanks

**Comment by JohnLucaJF** [comment]
Sorry, patiencs is a virtue, just need to wait till had processed all the mp3 !!!

**Comment by seanap** [comment]
Hey no worries, glad you got it figured out!

For clarification incase anyone else comes by; the docker will convert multiple mp3's to a single file chapterized m4b, however, the chapters created will be based on the mp3 files.  This script is NOT smart enough to source the real chapter time/names. Mainly because that database doesn't exsist (yet!)

Also, this docker _is supposed to_ use all available cores to do the converting. It works great on my Ubuntu VM with 6 cores assigned to it by proxmox, but I have not tested on a bare metal Linux os, nor a WSL windows docker installation. If performance is feeling sluggish you may need to manually set the core count (eg. `--jobs=4`) in the m4b-tool docker run command.

**Comment by dvdgorila** [comment]
This doesnt appear to be working for me. Im left with multiple folders each containing a chapter text file and an m4b for that chapter (converted from mp3) 

i'd like end up with 1 m4b. 

Here is a sample of the ouput. 

![folder structure](https://user-images.githubusercontent.com/5569832/213340067-be52a7b4-bdac-4188-a3e3-ff3152f4cd1a.jpg)

![docker output](https://user-images.githubusercontent.com/5569832/213340238-9d8406b8-11ac-4add-b376-3d6cfdf021ad.jpg)

**Comment by dvdgorila** [comment]
disregard, i had to create a folder with the book name and all mp3s inside.

**Comment by seanap** [comment]
Looks like each chapter was in it's own folder.  Haven't quite figured out how to script it to do this automatically, I wanted to have it rename the mp3 the chapter folder name then move it up a level, but couldn't get something that worked, so for now annoyingly you'll have to manually put all mp3's in 1 folder.  It should have kicked the book out to the Fix folder instead of processing, so something funky is happening.
