### ISSUE TITLE
Option to take m4b tool and produce list of chapters

### ISSUE THREAD

**Issue by Ozyman2456** [seanap/auto-m4b#48]
apologies if this is already possible, but looking through the guide I cannot see an option for this.

I wanted to taker a m4b container file and produce the .chpaters.txt so that editing chapter metadata will be much easier moving forward (throw he m4ba and chapters.txt into the merge folder to update the metadata). This process is super easy with audiobooks with single mp3's, but cant get a chapters.txt from a container that is already chapterised m4b

**Comment by seanap** [comment]
The auto-m4b-tool.sh script really isn't set up for that.  In line 86 you can add the m4b file type so the m4b book gets moved into the merge folder, but the problem is the script is set up to use the files as chapters not to read the embedded m4b chapters.  This may strip any existing chapters and just leave it as a monolith with a chapters.txt file with a single chapter.  It is possible to use ffmpeg to do what you are looking for but would require a pretty big redesign of this script.

What I do is use audiobookshelf to pull the complete metadata, pull the # of chapters and chapter names, and embed. If the book is in audible then ABS can match and pull everything for you, if your book isn't in audible then atleast ABS gives us a great gui for easily editing chapters (imo much easier than using the chapters.txt)

**Comment by Ozyman2456** [comment]
Hi, thanks for taking the time to get back to me.
Audiobookshelf was the answer - thank you!
