### ISSUE TITLE
Question: Docker Desktop on Windows

### ISSUE THREAD

**Issue by kyleviloria** [seanap/auto-m4b#6]
Although it's clear that auto-m4b is Linux only workflow, can auto-m4b be used on Windows via Docker Desktop (WSL2)?

If so, how are library location and other paths referred to?

**Comment by seanap** [comment]
I don't have any way to test  WSL, so I don't know for sure.  At it's core this is just ffmpeg, I've seen other similar dockers running on WSL so I would have to think that it should be possible.  You might run into an issue where any hardware accelerators (GPU) may not work due to driver/docker compatibility issues, but it should still run from CPU.

I've never used WSL, but I would think that the volume mapping would look something like this:

`-v c:\path\to\temp:/temp` 

If you try it out let me know how it goes.
